// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 02.09.2024, 22:30:17
const configMerger = require("D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/plugins/**/*.{js,ts,mjs}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/composables/**/*.{js,ts,mjs}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/utils/**/*.{js,ts,mjs}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/learning/project/Вёрстка и js/Заказы/jsonplaceholder/project/app.config.{js,ts,mjs}"] }));

module.exports = config
